### ISSUE TITLE
Incorrectly decodes ID3v2.3 UTF-16 names

### ISSUE THREAD

**Issue by bladeSk** [interbred-monkey/id3_reader#12]
Here are my test files. The song name should be `ずっと前 - Way Back`:
ID3v2.3 (UTF-16) http://8.brm.sk/t/id3v2.3%20UTF-16%20test.mp3 - doesn't work correctly, displays `Z0c0h0MR - Way Back`
ID3v2.4 (UTF-8) http://8.brm.sk/t/id3v2.4%20UTF-8%20test.mp3 - works correctly, displays `ずっと前 - Way Back`

**Comment by interbred-monkey** [comment]
Merged in the fix and seems to work fine.
