### ISSUE TITLE
Cannot find config

### ISSUE THREAD

**Issue by JakeChampion** [interbred-monkey/id3_reader#3]
I tried using this module with browserify and had this error.

`Error: Cannot find module './config/config.json' from '/Users/jakechampion/Projects/OfflineAudioOrg/OfflineAudio.github.io/node_modules/id3_reader/includes'`

**Comment by interbred-monkey** [comment]
I will take a look at this as soon as possible.

Thanks for letting me know.

**Comment by interbred-monkey** [comment]
@JakeChampion It seems that npm was not respecting the symlink I had put in place. I have merged in the change from @benkaiser to hard code the config file in place and I have published it to npm so hopefully this will fix the issue.
